# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-17 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(default=0)),
                ('state', models.CharField(default='true', max_length=50)),
                ('description', models.CharField(default='null', max_length=500)),
            ],
        ),
    ]
