# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-17 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='tid',
        ),
    ]
