# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-18 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_todoitem_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
