# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-18 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191018_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
