# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-20 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_todoitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='state',
            field=models.IntegerField(default=1, max_length=50),
        ),
    ]
