# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-20 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191020_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='state',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
